import pandas as pd


def fix_msd(morph,df):
    for index, row in df.iterrows():
        if morph.find(str(row["MSD"])) != -1:
            morph = str(row["TAG"]).upper()+morph[morph.find("|"):]
            morph = fix_morph(morph)
            break
    return morph


def fix_morph(morph):
    morph = morph.replace("NUMe","NUM")
    morph = morph.replace("num=singular","Number=Sing")
    morph = morph.replace("num=plural","Number=Plur")
    morph = morph.replace("gen=masculine","Gender=Masc")
    morph = morph.replace("gen=feminine","Gender=Fem")
    morph = morph.replace("type=preposition","AdpType=Prep")
    morph = morph.replace("tense=present","Tense=Pres")
    morph = morph.replace("mood=subjunctive","Mood=Sub")
    morph = morph.replace("mood=indicative","Mood=Ind")
    morph = morph.replace("person","Person")
    morph = morph.replace("type=indefinite","PronType=Ind")
    morph = morph.replace("|gen=common","")
    morph = morph.replace("type=comma","PunctType=Comm")
    morph = morph.replace("type=relative","PronType=Rel")
    morph = morph.replace("|num=invariable","")
    morph = morph.replace("type=personal","PronType=Prs")
    morph = morph.replace("|type=main","")
    morph = morph.replace("type=demonstrative","PronType=Dem")
    morph = morph.replace("type=period","PunctType=Peri")
    morph = morph.replace("|type=common","")
    morph = morph.replace("tense=future","Tense=Fut")
    morph = morph.replace("|tense=conditional","")
    morph = morph.replace("type=questionmark","PunctType=Qest")
    morph = morph.replace("punctenclose=close","PunctSide=Fin")
    morph = morph.replace("type=article","PronType=Art")
    morph = morph.replace("tense=present","Tense=Pres")
    morph = morph.replace("|type=qualificative","")
    morph = morph.replace("|type=coordinating","")
    morph = morph.replace("type=Personal","PronType=Prs")
    morph = morph.replace("|type=semiauxiliary","")
    morph = morph.replace("mood=imperative","Mood=Imp")
    morph = morph.replace("|neclass=organization","")
    morph = morph.replace("|type=proper","")
    morph = morph.replace("possessorpers","Person")
    morph = morph.replace("|possessornum=invariable","")
    morph = morph.replace("type=possessive","Poss=Yes")
    morph = morph.replace("|neclass=other","")
    morph = morph.replace("NUMr","NUM")
    morph = morph.replace("mood=participle","Mood=Par")
    morph = morph.replace("mood=infinitive","Mood=Inf")
    morph = morph.replace("|neclass=location","")
    morph = morph.replace("|type=auxiliary","")
    morph = morph.replace("|type=general","")
    morph = morph.replace("type=colon","PunctType=Colo")
    morph = morph.replace("|punctenclose=open","")
    morph = morph.replace("type=quotation","PunctType=Peri")
    morph = morph.replace("|type=subordinating","")
    morph = morph.replace("type=ordinal","NumType=Ord")
    morph = morph.replace("|neclass=Person","")
    morph = morph.replace("mood=gerund","Mood=Ger")
    morph = morph.replace("type=negative","Polarity=Neg")
    morph = morph.replace("type=semicolon","PunctType=Semi")
    morph = morph.replace("tense=imperfect","Tense=Imp")
    morph = morph.replace("type=interrogative","PronType=Int")
    morph = morph.replace("type=etc","PunctType=Comm")
    morph = morph.replace("possessorNumber=Plur","Number[psor]=Plur")
    morph = morph.replace("possessorNumber=Sing","Number[psor]=Sing")
    morph = morph.replace("polite=yes","Polite=Form")
    morph = morph.replace("case=nominative","Case=Nom")
    morph = morph.replace("case=dative","Case=Dat")
    morph = morph.replace("|type=other","")
    morph = morph.replace("INTn","INTJ")
    morph = morph.replace("case=accusative","Case=Acc")
    morph = morph.replace("|type=slash","")
    morph = morph.replace("type=hyphen","PunctType=Dash")
    morph = morph.replace("|type=currency","")
    morph = morph.replace("|type=unit","")
    morph = morph.replace("|type=percentag","")
    morph = morph.replace("type=exclamationmark","PunctType=Excl")
    morph = morph.replace("tense=past", "Tense=Past")
    morph = morph.replace("UPosTag=NUMe", "UPosTag=NUM")
    morph = morph.replace("type=partitive", "")
    morph = morph.replace("degree=superlative", "")
    morph = morph.replace("type=parenthesis", "PunctType=Brck")
    morph = morph.replace("case=oblique", "")
    morph = morph.replace("degree=evaluative", "")
    morph = morph.replace("type=exclamative", "")
    morph = morph.replace("type=squarebracket", "")
    morph = morph.replace("NUMe","NUM")
    morph = morph.replace("","")
    return morph